# https://www.programmingwithwolfgang.com/create-a-docker-image-in-an-azure-devops-ci-pipeline/

name: CI
trigger:
  - dev

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Build'
    jobs:
      - job: 'Build'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'vikekh/cv'
              command: 'build'
              Dockerfile: './src/Vikekh.Cv.Web/Dockerfile'
              buildContext: '$(Build.Repository.LocalPath)'
              tags: latest
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'vikekh/cv'
              command: 'push'
              tags: latest
  - stage: 'Deploy'
    jobs:
      - job: 'Deploy'
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(AzureSubscription)
              appName: $(AzureAppName)
              containers: 'vikekh/cv:latest'
              multicontainerConfigFile: './docker-compose.prod.yml'