# https://www.programmingwithwolfgang.com/create-a-docker-image-in-an-azure-devops-ci-pipeline/

name: CI
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Build'
    jobs:
      - job: 'Build'
        steps:
          - task: 'Docker@2'
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'vikekh/cv'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'vikekh/cv'
              command: 'push'
              tags: |
                $(Build.BuildId)
                latest